[project]
name = "nepali-facebook-data-annotation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.0",
    "pillow>=11.2.1",
    "streamlit>=1.45.1",
    "supabase>=2.15.3",
]
